# [General]\
# Mirror schedule:
schedule:
  '01:00:00 pm' :
    - everyday
  '01:00:00 am':
    - monday
    - tueday
    - wednesday
    - thursday
    - friday

# [daemon]
# This configuration file
source:
destination:

# Log file location:
logPath:

# The level of logging that should be sent to the log file.
# This value is passed to the logging library. Any positive
# integer value is valid but most common cases are:
# - 10 - Debug
# - 20 - Info
# - 30 - Warnings
# - 40 - Error
# - 50 - Critical
logging: 20

# [git]
gitRepo:
