# [General]\
# Mirror schedule:
schedule:
  '01:00:00 pm' :
    - everyday
  '01:00:00 am':
    - monday
    - tueday
    - wednesday
    - thursday
    - friday

IGNORE_dir: []
IGNORE_fileType: []

# [daemon]
# The pidFile is the location where the daemon will store its process id. If
# this file is removed while the daemon is running, it will shutdown cleanly
# after the next pass through the event processing loop.
pidFile: ~/shotgunEventDaemon.pid

# This configuration file
source: /mnt/drive/myRepo
destination: ~/GIT/myRepo

# Log mode:
# 0 > Off
# 1 > On
logMode: 1

# The path where to put log files
logPath: /var/log

# The name of the daemon log file. The setup is for 10 log files that rotate
# every night at midnight
logFile: filemirror.log

# Number of seconds to wait before checking new file after each batch of events
# is done processing
fetch_interval: 60

# The level of logging that should be sent to the log file.
# This value is passed to the logging library. Any positive
# integer value is valid but most common cases are:
# - 10 - Debug
# - 20 - Info
# - 30 - Warnings
# - 40 - Error
# - 50 - Critical
logLevel: 10

# [git]
git:
  url:
  path:
  branch:
  remote:
  deploy:
